attempted to fix multi selection reconnected
ossia/score pull request #1356
Opened 2022-02-04 16:28 UTC by RobinMontferme

Tried to fix issue #950

Crashes [here](https://github.com/ossia/score/compare/device-explorer-bugfixes?expand=1#diff-822c4bdbc71cc9b867292c08954c5c0aa2cab0b57e52c8639ce441093a77d625R679) :
```
while (p && !p->is<Device::DeviceSettings>())
```
while trying to use `std::pair<Device::DeviceCapas, bool>getCapas(Device::Node* p, const Device::DeviceList& lst)`

called from [here](https://github.com/ossia/score/compare/device-explorer-bugfixes?expand=1#diff-822c4bdbc71cc9b867292c08954c5c0aa2cab0b57e52c8639ce441093a77d625R756):
```
int selectionSize = m_ntView->selectedIndexes().size();
      bool validSelection = true;
      for (int i = 0; i < selectionSize; i++)
      {
        //BUG: crashes here
        const auto [capas, aDeviceIsSelected] = getCapas(
            &m->nodeFromModelIndex(m_ntView->selectedIndexes().at(i)),
            m->deviceModel().list());
```

2022-02-10 20:42 UTC, jcelerier requested changes

2022-02-10 20:42 UTC, jcelerier commented on src/plugins/score-plugin-deviceexplorer/Explorer/Explorer/DeviceExplorerWidget.cpp
> +      qDebug() << "Selection size" << selection.size();
remove the qdebug pls :)

2022-02-10 20:42 UTC, jcelerier commented on src/plugins/score-plugin-deviceexplorer/Explorer/Explorer/DeviceExplorerWidget.cpp
> +        proxyModel()->mapToSource(m_ntView->selectedIndexes().at(i)));
well spotted, thanks !

2022-02-11 13:48 UTC, RobinMontferme commented on src/plugins/score-plugin-deviceexplorer/Explorer/Explorer/DeviceExplorerWidget.cpp
> +      qDebug() << "Selection size" << selection.size();
Done!

2022-02-11 16:13 UTC, merged